spring:
  application:
    name: test-task

  datasource:
    url: jdbc:postgresql://localhost:5555/postgres
    username: postgres
    password: seva2201
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      properties:
        hibernate:
          format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

token:
  jwt: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
